### ISSUE TITLE
Кодировка в возвращаемых данных Google Adwords

### ISSUE THREAD

**Issue by JuliaDoshlova** [selesnow/publications#1]
Алексей, здравствуйте! Использую библиотеку RAdwords. В возвращаемых данных русские символы отображаются в виде не читаемых иероглифов, что-то с кодировкой. Но я не понимаю, где поправить. Помогите пожалуйста. Латиница отображается корректно. При этом данные с Яндекс.Директ выгружаются корректно, в том числе и кириллица. Проблема только в Google Adwords. Алексей, может быть вы сталкивались с подобным, сможете помочь?

**Comment by selesnow** [comment]
Здравствуйте, это проблема несколько месяцев назад появилась в пакете RAdwords, о том как это я решить я рассказывал в вебинарах, вот варианты решения:

1. использовать двойное кодирование через фуекцию iconv, пример можно посмотреть перейдя по [ссылке](https://raw.githubusercontent.com/selesnow/publications/master/code_example/webpromo_now_2018/2-google-ads.R).

2. Использовать пакет adwordsR, пример есть [тут](https://raw.githubusercontent.com/selesnow/publications/master/code_example/matemarketing/2-google-ads.R)

**Comment by JuliaDoshlova** [comment]
Алексей, благодарю вас!
Всё решилось с помощью iconv.
